const storageKey = 'cubex-session-v1';
let solves = JSON.parse(localStorage.getItem(storageKey) || '[]');
let currentCube = '3x3';
let timerState = 'stopped';
let pressTimer;
let startTime;
let interval;
let inspectionInterval;
let soundEnabled = localStorage.getItem('cubex-sound') !== 'off';
const backgroundKey = 'cubesons-timer-background';
const accentKey = 'cubesons-accent';
const $ = (selector) => document.querySelector(selector);
const clock = $('#timer-clock');
const timerZone = $('#touch-trigger');
function applyTheme(theme) { document.body.dataset.theme = theme; document.body.classList.toggle('dark-mode', theme === 'dark'); $('#theme-toggle').textContent = theme === 'dark' ? 'Light mode' : 'Dark mode'; localStorage.setItem('cubex-theme', theme); }
function beep() { if (!soundEnabled || !window.AudioContext) return; const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = 640; gain.gain.value = 0.04; oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.08); }
function applyCustomization() { const background = localStorage.getItem(backgroundKey); const accent = localStorage.getItem(accentKey); const panel = $('#timer-panel'); if (background) { panel.style.backgroundImage = `url(${background})`; panel.classList.add('custom-bg'); } if (accent) { document.documentElement.style.setProperty('--lime', accent); $('#accent-picker').value = accent; } }
function formatTime(value) { return value === 'DNF' ? 'DNF' : value == null ? '--' : `${value.toFixed(2)}s`; }
function numericSolves() { return solves.filter((value) => typeof value === 'number' && Number.isFinite(value)); }
function makeScramble() {
  const faces = ['R', 'L', 'U', 'D', 'F', 'B']; const modifiers = ['', "'", '2'];
  const length = currentCube === '2x2' ? 11 : currentCube === '4x4' ? 40 : currentCube === '5x5' ? 50 : 20;
  const result = []; let previous = '';
  while (result.length < length) { const face = faces[Math.floor(Math.random() * faces.length)]; if (face !== previous) { result.push(face + modifiers[Math.floor(Math.random() * modifiers.length)]); previous = face; } }
  $('#scramble').textContent = result.join('  ');
}
function averages() {
  const clean = numericSolves(); const sorted = [...clean].sort((a, b) => a - b); const mean = clean.length ? clean.reduce((sum, value) => sum + value, 0) / clean.length : null; const middle = Math.floor(sorted.length / 2);
  const median = sorted.length ? (sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2) : null;
  const average = (count) => solves.length >= count && solves.slice(0, count).every((value) => typeof value === 'number') ? solves.slice(0, count).sort((a, b) => a - b).slice(1, -1).reduce((sum, value) => sum + value, 0) / (count - 2) : null;
  return { mean, median, ao3: average(3), ao5: average(5), ao12: average(12), best: sorted[0] || null };
}
function solveRows(list, limit) { return list.slice(0, limit).map((time, index) => `<div class="solve-row"><span><small>#${list.length - index}</small> ${index === 0 ? 'Latest solve' : 'Solve'}</span><span class="solve-actions"><strong>${formatTime(time)}</strong><button class="delete-solve" data-index="${index}" title="Delete solve">×</button></span></div>`).join(''); }
function render() {
  const stats = averages(); $('#mini-pb').textContent = formatTime(stats.best); $('#mini-ao5').textContent = formatTime(stats.ao5); $('#mini-ao12').textContent = formatTime(stats.ao12); $('#mini-mean').textContent = formatTime(stats.mean); $('#mini-last').textContent = formatTime(solves[0]); $('#solve-count').textContent = `${solves.length} solve${solves.length === 1 ? '' : 's'}`;
  $('#recent-solves').innerHTML = solves.length ? solveRows(solves, 4) : '<p class="empty-state">Your first solve is waiting.</p>'; $('#history-list').innerHTML = solves.length ? solveRows(solves) : '<p class="empty-state">No solves in this session yet.</p>';
  $('#stat-mean').textContent = formatTime(stats.mean); $('#stat-median').textContent = formatTime(stats.median); $('#stat-ao3').textContent = formatTime(stats.ao3); $('#stat-ao12').textContent = formatTime(stats.ao12); $('#stat-best').textContent = formatTime(stats.best); $('#stat-total').textContent = solves.length; renderChart(); renderInsights();
}
function renderChart() { const values = numericSolves().slice(0, 12).reverse(); const max = Math.max(...values, 1); $('#chart-best').textContent = values.length ? `best ${formatTime(Math.min(...values))}` : 'No data'; $('#chart').innerHTML = values.length ? values.map((value, index) => `<div class="bar" style="height:${Math.max(7, value / max * 82)}%"><span>${index + 1}</span></div>`).join('') : '<p class="empty-state">Solve a few cubes to see your pace.</p>'; }
function renderInsights() {
  const values = numericSolves(); const sorted = [...values].sort((a, b) => a - b); const best = sorted[0]; const worst = sorted[sorted.length - 1]; const mean = values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
  if (!mean) { $('#analysis-title').textContent = 'Solve a few cubes to unlock your read.'; $('#analysis-copy').textContent = 'Your first sessions will build the baseline for personalized feedback.'; $('#analysis-progress-label').textContent = 'PB gap will appear here'; $('#stat-consistency').textContent = '--'; $('#stat-trend').textContent = '--'; $('#stat-range').textContent = '--'; return; }
  const variance = values.reduce((sum, value) => sum + ((value - mean) ** 2), 0) / values.length; const consistency = Math.max(0, Math.min(100, 100 - (Math.sqrt(variance) / mean * 100))); const recent = values.slice(0, 5); const previous = values.slice(5, 10); const recentMean = recent.reduce((sum, value) => sum + value, 0) / recent.length; const previousMean = previous.length ? previous.reduce((sum, value) => sum + value, 0) / previous.length : recentMean; const trend = previousMean ? ((recentMean - previousMean) / previousMean) * 100 : 0; const gap = mean - best; const progress = Math.max(6, Math.min(100, (best / mean) * 100));
  const title = values.length < 3 ? 'Baseline is forming.' : consistency < 70 ? 'Consistency is your next win.' : trend < -3 ? 'Your recent pace is improving.' : trend > 3 ? 'Recent pace needs a reset.' : 'You are holding a steady pace.';
  const advice = values.length < 3 ? 'Keep the session going. Three solves unlock a stronger read.' : consistency < 70 ? 'Focus on turning your slow solves into controlled solves before chasing a faster single.' : trend < -3 ? 'Keep the same rhythm. Your latest block is trending faster than the previous one.' : trend > 3 ? 'Slow down your first turns and protect your cross. Your latest block is slightly slower.' : 'Keep your turning rhythm and target your biggest outlier next.';
  $('#analysis-title').textContent = title; $('#analysis-copy').textContent = advice; $('#analysis-progress').style.width = `${progress}%`; $('#analysis-progress-label').textContent = `${formatTime(gap)} between your mean and PB`; $('#stat-consistency').textContent = `${consistency.toFixed(0)}%`; $('#consistency-copy').textContent = consistency >= 85 ? 'Very repeatable solves.' : consistency >= 70 ? 'Good control, trim the outliers.' : 'Wide spread. Build a calmer rhythm.'; $('#stat-trend').textContent = `${trend > 0 ? '+' : ''}${trend.toFixed(1)}%`; $('#trend-copy').textContent = trend < -3 ? 'Faster than your previous block.' : trend > 3 ? 'Slower than your previous block.' : 'Holding steady against your previous block.'; $('#stat-range').textContent = formatTime(worst - best); $('#range-copy').textContent = `Best ${formatTime(best)} / slowest ${formatTime(worst)}.`;
}
function startInspection() { if (timerState !== 'stopped') return; clearInterval(inspectionInterval); let remaining = 15; timerState = 'inspecting'; clock.textContent = remaining.toFixed(2); $('#timer-state').textContent = 'INSPECTION'; inspectionInterval = setInterval(() => { remaining -= 0.1; clock.textContent = Math.max(remaining, 0).toFixed(2); if (remaining <= 0) { clearInterval(inspectionInterval); timerState = 'stopped'; clock.textContent = '0.00'; $('#timer-state').textContent = 'INSPECTION OVER'; } }, 100); }
function beginHold() { if (timerState === 'running') return stopTimer(); if (timerState !== 'stopped') return; timerState = 'holding'; timerZone.classList.add('ready'); $('#timer-state').textContent = 'RELEASE TO START'; pressTimer = setTimeout(() => { timerState = 'ready'; $('#timer-state').textContent = 'READY'; }, 350); }
function releaseHold() { clearTimeout(pressTimer); if (timerState === 'holding') { timerState = 'stopped'; timerZone.classList.remove('ready'); $('#timer-state').textContent = 'HOLD TO START'; return; } if (timerState === 'ready') { timerState = 'running'; timerZone.classList.remove('ready'); timerZone.classList.add('running'); $('#timer-state').textContent = 'RUNNING'; startTime = performance.now(); interval = setInterval(() => { clock.textContent = ((performance.now() - startTime) / 1000).toFixed(2); }, 10); } }
function stopTimer() { clearInterval(interval); const time = Number(clock.textContent); if (time > 0) solves.unshift(time); localStorage.setItem(storageKey, JSON.stringify(solves)); timerState = 'stopped'; timerZone.classList.remove('running'); $('#timer-state').textContent = 'HOLD TO START'; beep(); makeScramble(); render(); }
document.querySelectorAll('.nav-item, .text-button, .quick-settings').forEach((button) => button.addEventListener('click', () => { const target = button.dataset.target; if (!target) return; document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active-view', view.id === target)); document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.target === target)); $('#page-title').textContent = target === 'timer' ? 'Timer' : target[0].toUpperCase() + target.slice(1); }));
$('#cube-type').addEventListener('change', (event) => { currentCube = event.target.value; makeScramble(); }); $('#new-scramble').addEventListener('click', makeScramble); $('#inspection-start').addEventListener('click', startInspection); $('#plus-two').addEventListener('click', () => { if (typeof solves[0] === 'number') { solves[0] += 2; localStorage.setItem(storageKey, JSON.stringify(solves)); render(); } }); $('#dnf').addEventListener('click', () => { if (solves.length) { solves[0] = 'DNF'; localStorage.setItem(storageKey, JSON.stringify(solves)); render(); } }); $('#clear-btn').addEventListener('click', () => { if (solves.length && confirm('Clear this session?')) { solves = []; localStorage.removeItem(storageKey); render(); } });
document.addEventListener('click', (event) => { const button = event.target.closest('.delete-solve'); if (button) { solves.splice(Number(button.dataset.index), 1); localStorage.setItem(storageKey, JSON.stringify(solves)); render(); } });
$('#theme-toggle').addEventListener('click', () => applyTheme(document.body.dataset.theme === 'dark' ? 'light' : 'dark'));
$('#sound-toggle').addEventListener('click', () => { soundEnabled = !soundEnabled; localStorage.setItem('cubex-sound', soundEnabled ? 'on' : 'off'); $('#sound-toggle').textContent = soundEnabled ? 'Sound on' : 'Sound off'; });
$('#bg-upload').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { localStorage.setItem(backgroundKey, reader.result); applyCustomization(); } catch (error) { alert('This image is too large. Please choose a smaller image.'); } }; reader.readAsDataURL(file); });
$('#accent-picker').addEventListener('input', (event) => { document.documentElement.style.setProperty('--lime', event.target.value); localStorage.setItem(accentKey, event.target.value); });
$('#clear-bg').addEventListener('click', () => { localStorage.removeItem(backgroundKey); $('#timer-panel').style.backgroundImage = ''; $('#timer-panel').classList.remove('custom-bg'); $('#bg-upload').value = ''; });
function exportSession() { const csv = ['Solve,Time'].concat(solves.map((value, index) => `${solves.length - index},${formatTime(value)}`)).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'cubesons-session.csv'; link.click(); URL.revokeObjectURL(link.href); }
$('#export-btn').addEventListener('click', exportSession); $('#settings-export').addEventListener('click', exportSession);
$('#settings-clear').addEventListener('click', () => { if (solves.length && confirm('Clear all session solves?')) { solves = []; localStorage.removeItem(storageKey); render(); } });
timerZone.addEventListener('pointerdown', (event) => { event.preventDefault(); beginHold(); }); timerZone.addEventListener('pointerup', (event) => { event.preventDefault(); releaseHold(); }); timerZone.addEventListener('pointerleave', () => { if (timerState === 'holding' || timerState === 'ready') releaseHold(); }); window.addEventListener('keydown', (event) => { if (event.code === 'Space' && !event.repeat) { event.preventDefault(); beginHold(); } if (event.key.toLowerCase() === 'r') makeScramble(); }); window.addEventListener('keyup', (event) => { if (event.code === 'Space') { event.preventDefault(); releaseHold(); } });
applyTheme(localStorage.getItem('cubex-theme') || 'dark'); $('#sound-toggle').textContent = soundEnabled ? 'Sound on' : 'Sound off'; applyCustomization(); makeScramble(); render();
window.setTimeout(() => $('#splash-screen').classList.add('is-hidden'), 1150);
